name: release
on:
  push:
    branches:
      - stedi-main
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: placeholder
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm i
        env:
          GITHUB_TOKEN: ${{secrets.PUBLIC_PACKAGE_GITHUB_TOKEN}}
      - run: npm run test #test command builds JSONata in its posttest script
      - run: npm run release
        env:
          GIT_AUTHOR_NAME: ${{steps.import_gpg.outputs.name}}
          GIT_COMMITTER_NAME: ${{steps.import_gpg.outputs.name}}
          GIT_AUTHOR_EMAIL: ${{steps.import_gpg.outputs.email}}
          GIT_COMMITTER_EMAIL: ${{steps.import_gpg.outputs.email}}
          GITHUB_TOKEN: ${{secrets.PUBLIC_PACKAGE_GITHUB_TOKEN}}